// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/protobuf/descriptor.proto

#ifndef RPCZ_google_2fprotobuf_2fdescriptor_2eproto__INCLUDED
#define RPCZ_google_2fprotobuf_2fdescriptor_2eproto__INCLUDED

#include <string>
#include <rpcz/service.hpp>

namespace google {
namespace protobuf {
class ServiceDescriptor;
class MethodDescriptor;
}  // namespace protobuf
}  // namespace google
namespace rpcz {
class rpc;
class closure;
class rpc_channel;
}  //namesacpe rpcz
#include "google/protobuf/descriptor.pb.h"

namespace google {
namespace protobuf {
void rpcz_protobuf_AssignDesc_google_2fprotobuf_2fdescriptor_2eproto();
void rpcz_protobuf_ShutdownFile_google_2fprotobuf_2fdescriptor_2eproto();


}  // namespace protobuf
}  // namespace google
#endif  // RPCZ_google_2fprotobuf_2fdescriptor_2eproto__INCLUDED
